version: "3.8"

services:

  mysqldb:
    container_name: mysqldb
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=employee
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql
    networks:
      springboot-mysql-net:

  webservices:
    container_name: webservices
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8089:8089
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/employee?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true",
          "spring.datasource.username" : "root",
          "spring.datasource.password" : "root",
          "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",
          "spring.jpa.hibernate.ddl-auto" : "update",
          "spring.datasource.driver-class-name":"com.mysql.cj.jdbc.Driver",
          "server.address":"0.0.0.0",
          "server.port":"8089"
        }'
    links:
      - mysqldb
    networks:
      springboot-mysql-net:
    restart: on-failure

volumes:
  data:

networks:
  springboot-mysql-net:
